version: "3"
services:
  redis-test:
    image: "redis"
    restart: always
    container_name: "redis-test"
    ports:
      - 15001:6379
    volumes:
      - /home/redistest:/data
    command: ["redis-server", "--requirepass", "123456"]
# docker run -itd --restart=always --name redis-test1 -p 15002:6379 -v /home/redistest1:/data redis redis-server --requirepass 123456
